### ISSUE TITLE
No module named boto

### ISSUE THREAD

**Issue by emoragaf** [puckel/docker-airflow#102]
I added "s3" as an Extra Package to the dockerfile, and then ran:
`docker build --rm -t puckel/docker-airflow .`

The build shows that boto is installed

But i keep getting the "Broken DAG: [/usr/local/airflow/dags/MyDag.py] No module named boto" Error when i load DAGs that use S3Hook

**Comment by davideberdin** [comment]
I think it requires to be installed separately: in the Dockerfile, insert ```pip install boto3 && pip install boto```. They should be the same package but to be careful I installed both and my problem was solved.

**Comment by emoragaf** [comment]
i added `pip install boto3 && pip install boto` to the dockerfile. The docker build log shows that boto is installed.
But when loading dags, the dependencies are not met. If i exec the pip install to the running container it works fine

**Comment by davoscollective** [comment]
To me this sounds like the user environment where you've added the python packages is different to the one the airflow services are running under, given that you can manually install boto once the docker container is running. 

I don't think you should edit the dockerfile, I think your python packages should go in a /requirements.txt file. 
In the entrypoint.sh script there is a part where it checks if that file exists, and then pip installs modules listed in it.   See: https://github.com/puckel/docker-airflow/blob/master/script/entrypoint.sh#L26
That file probably needs to be copied to the container root. at least, the script is expecting it to be there.

That script is running as the airflow user, because at the end of the dockerfile, it is setting the user, and then running the entrypoint.sh.

**Comment by emoragaf** [comment]
> That script is running as the airflow user, because at the end of the dockerfile, it is setting the user, and then running the entrypoint.sh.

This was the issue

**Comment by sphimmer** [comment]
I am running into this issue, what was the solution? it seems to still happen with the bot3, boto, and botocore modules added to the requirements.txt file. while all the other modules can be imported just fine. boto3 is still not able to be found

**Comment by tommydangerous** [comment]
Happening to me as well.

**Comment by omarfessi** [comment]
> > That script is running as the airflow user, because at the end of the dockerfile, it is setting the user, and then running the entrypoint.sh.
> 
> This was the issue

How to fix that issue please ?

**Comment by 94929** [comment]
I had the same issue and resolved it by placing a requirements.txt under the filesystem of the docker image.

The procedure is given below:
1. Create requirements.txt and put the package name which you want to install (boto3 in this case)
2. Run the docker image, make sure you mount the requirements.txt to docker.
`docker run -d -p 8080:8080 -v /home/user/requirements.txt:/requirements.txt puckel/docker-airflow webserver`

Hope this helps.
